version: "3"

services:
  app:
    build: app-test
    restart: on-failure
    network_mode: "host"
  salt:
    build: salt-test
    restart: on-failure
    network_mode: "host"
  mongo:
    image: mongo:4.0
    restart: always
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example